codegen: Update assert_impl
https://github.com/rust-lang/rust/commit/9c1c0bfcb23d5411b6cb2b11f209fc6a93dbf97a broke this.

```
error[E0277]: the type `(dyn Any + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   --> src/gen/assert_impl.rs:22:26
    |
22  |     assert_unwind_safe::<crate::future::ResumeTy>();
    |                          ^^^^^^^^^^^^^^^^^^^^^^^ `(dyn Any + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
    |
    = help: within `Context<'static>`, the trait `RefUnwindSafe` is not implemented for `(dyn Any + 'static)`, which is required by `future::ResumeTy: UnwindSafe`
    = note: required because it appears within the type `&'static mut (dyn Any + 'static)`
note: required because it appears within the type `core::task::wake::ExtData<'static>`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/wake.rs:225:6
    |
225 | enum ExtData<'a> {
    |      ^^^^^^^
note: required because it appears within the type `Context<'static>`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/wake.rs:236:12
    |
236 | pub struct Context<'a> {
    |            ^^^^^^^
    = note: required for `NonNull<Context<'static>>` to implement `UnwindSafe`
note: required because it appears within the type `future::ResumeTy`
   --> src/lib.rs:328:16
    |
328 |     pub struct ResumeTy(pub(crate) NonNull<Context<'static>>);
    |                ^^^^^^^^
note: required by a bound in `assert_unwind_safe`
   --> src/gen/assert_impl.rs:16:35
    |
16  | fn assert_unwind_safe<T: ?Sized + std::panic::UnwindSafe>() {}
    |                                   ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `assert_unwind_safe`

error[E0277]: the type `(dyn Any + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   --> src/gen/assert_impl.rs:23:30
    |
23  |     assert_ref_unwind_safe::<crate::future::ResumeTy>();
    |                              ^^^^^^^^^^^^^^^^^^^^^^^ `(dyn Any + 'static)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
    |
    = help: within `future::ResumeTy`, the trait `RefUnwindSafe` is not implemented for `(dyn Any + 'static)`, which is required by `future::ResumeTy: RefUnwindSafe`
    = note: required because it appears within the type `&'static mut (dyn Any + 'static)`
note: required because it appears within the type `core::task::wake::ExtData<'static>`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/wake.rs:225:6
    |
225 | enum ExtData<'a> {
    |      ^^^^^^^
note: required because it appears within the type `Context<'static>`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/task/wake.rs:236:12
    |
236 | pub struct Context<'a> {
    |            ^^^^^^^
    = note: required because it appears within the type `*const Context<'static>`
note: required because it appears within the type `NonNull<Context<'static>>`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/non_null.rs:73:12
    |
73  | pub struct NonNull<T: ?Sized> {
    |            ^^^^^^^
note: required because it appears within the type `future::ResumeTy`
   --> src/lib.rs:328:16
    |
328 |     pub struct ResumeTy(pub(crate) NonNull<Context<'static>>);
    |                ^^^^^^^^
note: required by a bound in `assert_ref_unwind_safe`
   --> src/gen/assert_impl.rs:17:39
    |
17  | fn assert_ref_unwind_safe<T: ?Sized + std::panic::RefUnwindSafe>() {}
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `assert_ref_unwind_safe`
```